<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKl5hdbV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKl5hdbV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKl5hdbV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKl5hdbV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKl5hdbV\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kl5hdbV',
    'container.build_id' => '500c43e2',
    'container.build_time' => 1639349132,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKl5hdbV');
