<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'add_categoria' => [[], ['_controller' => 'App\\Controller\\CategoriaController::add'], [], [['text', '/categoria/save']], [], [], []],
    'list_categoria' => [[], ['_controller' => 'App\\Controller\\CategoriaController::listCategorias'], [], [['text', '/categoria/list']], [], [], []],
    'get_categoria' => [[], ['_controller' => 'App\\Controller\\CategoriaController::getCategoria'], [], [['text', '/categoria/get']], [], [], []],
    'update_categoria' => [[], ['_controller' => 'App\\Controller\\CategoriaController::update_categoria'], [], [['text', '/categoria/update']], [], [], []],
    'delete_categoria' => [[], ['_controller' => 'App\\Controller\\CategoriaController::delete_categoria'], [], [['text', '/categoria/delete']], [], [], []],
    'producto_get' => [[], ['_controller' => 'App\\Controller\\ProductoController::producto_get'], [], [['text', '/producto/get']], [], [], []],
    'producto_list' => [[], ['_controller' => 'App\\Controller\\ProductoController::producto_list'], [], [['text', '/producto/list']], [], [], []],
    'producto_save' => [[], ['_controller' => 'App\\Controller\\ProductoController::producto_save'], [], [['text', '/producto/save']], [], [], []],
    'venta' => [[], ['_controller' => 'App\\Controller\\VentaController::index'], [], [['text', '/venta']], [], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], [], []],
    'api_graphql_entrypoint' => [[], ['_controller' => 'api_platform.graphql.action.entrypoint', '_graphql' => true], [], [['text', '/api/graphql']], [], [], []],
    'api_graphql_graphiql' => [[], ['_controller' => 'api_platform.graphql.action.graphiql', '_graphql' => true], [], [['text', '/api/graphql/graphiql']], [], [], []],
    'api_graphql_graphql_playground' => [[], ['_controller' => 'api_platform.graphql.action.graphql_playground', '_graphql' => true], [], [['text', '/api/graphql/graphql_playground']], [], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], [], []],
    'api_categorias_get_collection' => [['_format'], ['_controller' => 'api_platform.action.get_collection', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\Entity\\Categoria', '_api_identifiers' => ['id'], '_api_has_composite_identifier' => false, '_api_collection_operation_name' => 'get'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/categorias']], [], [], []],
    'api_categorias_post_collection' => [['_format'], ['_controller' => 'api_platform.action.post_collection', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\Entity\\Categoria', '_api_identifiers' => ['id'], '_api_has_composite_identifier' => false, '_api_collection_operation_name' => 'post'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/categorias']], [], [], []],
    'api_categorias_get_item' => [['id', '_format'], ['_controller' => 'api_platform.action.get_item', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\Entity\\Categoria', '_api_identifiers' => ['id'], '_api_has_composite_identifier' => false, '_api_item_operation_name' => 'get'], [], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '[^/\\.]++', 'id', true], ['text', '/api/categorias']], [], [], []],
    'api_categorias_delete_item' => [['id', '_format'], ['_controller' => 'api_platform.action.delete_item', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\Entity\\Categoria', '_api_identifiers' => ['id'], '_api_has_composite_identifier' => false, '_api_item_operation_name' => 'delete'], [], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '[^/\\.]++', 'id', true], ['text', '/api/categorias']], [], [], []],
    'api_categorias_put_item' => [['id', '_format'], ['_controller' => 'api_platform.action.put_item', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\Entity\\Categoria', '_api_identifiers' => ['id'], '_api_has_composite_identifier' => false, '_api_item_operation_name' => 'put'], [], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '[^/\\.]++', 'id', true], ['text', '/api/categorias']], [], [], []],
    'api_categorias_patch_item' => [['id', '_format'], ['_controller' => 'api_platform.action.patch_item', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\Entity\\Categoria', '_api_identifiers' => ['id'], '_api_has_composite_identifier' => false, '_api_item_operation_name' => 'patch'], [], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '[^/\\.]++', 'id', true], ['text', '/api/categorias']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
];
