version: '3.7'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./source:/var/www/html
        ports:
            - 9000:8000
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_DATABASE: lol
            MYSQL_USER: lol
            MYSQL_PASSWORD: noquiero
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - 33069:3306
        volumes:
            - datos:/var/lib/mysql
        depends_on:
            - php
    phpMyAdmin:
        image: phpmyadmin:latest
        container_name: phpMyAdmin
        environment:
            MYSQL_ROOT_PASSWORD: admin
            PMA_HOST: mysql
        depends_on:
            - mysql
        ports:
            - 8080:80
volumes: 
    .:
    datos:
