<?php

namespace ContainerQliV2yX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XVLSGR1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XVLSGR1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XVLSGR1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoriaController::getCategoria' => ['privates', '.service_locator.hT2Kv93', 'get_ServiceLocator_HT2Kv93Service', true],
            'App\\Controller\\CategoriaController::listCategorias' => ['privates', '.service_locator.hT2Kv93', 'get_ServiceLocator_HT2Kv93Service', true],
            'App\\Controller\\ProductoController::producto_get' => ['privates', '.service_locator.hT2Kv93', 'get_ServiceLocator_HT2Kv93Service', true],
            'App\\Controller\\ProductoController::producto_list' => ['privates', '.service_locator.hT2Kv93', 'get_ServiceLocator_HT2Kv93Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CategoriaController:getCategoria' => ['privates', '.service_locator.hT2Kv93', 'get_ServiceLocator_HT2Kv93Service', true],
            'App\\Controller\\CategoriaController:listCategorias' => ['privates', '.service_locator.hT2Kv93', 'get_ServiceLocator_HT2Kv93Service', true],
            'App\\Controller\\ProductoController:producto_get' => ['privates', '.service_locator.hT2Kv93', 'get_ServiceLocator_HT2Kv93Service', true],
            'App\\Controller\\ProductoController:producto_list' => ['privates', '.service_locator.hT2Kv93', 'get_ServiceLocator_HT2Kv93Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CategoriaController::getCategoria' => '?',
            'App\\Controller\\CategoriaController::listCategorias' => '?',
            'App\\Controller\\ProductoController::producto_get' => '?',
            'App\\Controller\\ProductoController::producto_list' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoriaController:getCategoria' => '?',
            'App\\Controller\\CategoriaController:listCategorias' => '?',
            'App\\Controller\\ProductoController:producto_get' => '?',
            'App\\Controller\\ProductoController:producto_list' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
