<?php

namespace ContainerQliV2yX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Cache_SubscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.cache.subscription' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\AdapterInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.graphql.cache.subscription'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('b+OAAtBRQN', 0, $container->getParameter('container.build_id'), ($container->targetDir.''.'/pools/system'), ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
    }
}
