<?php

namespace ContainerQliV2yX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProductoController' shared autowired service.
     *
     * @return \App\Controller\ProductoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProductoController.php';

        $container->services['App\\Controller\\ProductoController'] = $instance = new \App\Controller\ProductoController(($container->privates['App\\Repository\\ProductoRepository'] ?? $container->load('getProductoRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ProductoController', $container));

        return $instance;
    }
}
