<?php

namespace ContainerQliV2yX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVentaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VentaController' shared autowired service.
     *
     * @return \App\Controller\VentaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/VentaController.php';

        $container->services['App\\Controller\\VentaController'] = $instance = new \App\Controller\VentaController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\VentaController', $container));

        return $instance;
    }
}
