<?php

namespace ContainerKl5hdbV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CategoriaController' shared autowired service.
     *
     * @return \App\Controller\CategoriaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CategoriaController.php';

        $container->services['App\\Controller\\CategoriaController'] = $instance = new \App\Controller\CategoriaController(($container->privates['App\\Repository\\CategoriaRepository'] ?? $container->load('getCategoriaRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\CategoriaController', $container));

        return $instance;
    }
}
